### ISSUE TITLE
Fix the ZMQ disconnection issues

### ISSUE THREAD

**Issue by SGrondin** [APIAnalytics/HARchiver#6]
As described in the spec: https://github.com/Mashape/analytics-agent-spec/blob/master/README.md

**Comment by SGrondin** [comment]
This is almost done and the techniques I've used will become the guidelines for all the agents using ZMQ.

**Comment by ahmadnassri** [comment]
a soon as done, mark the other tickets "critical" and notify the rest of the team

**Comment by SGrondin** [comment]
Done and deployed to staging

**Comment by SGrondin** [comment]
Deployed to prod. I tested it by redeploying the socket servers and I can confirm that it works great.
