### ISSUE TITLE
error while loading shared libraries: libcrypto.so.0.9.8

### ISSUE THREAD

**Issue by jupalls** [APIAnalytics/HARchiver#7]
While starting the /harchiver getting the following error:
error while loading shared libraries: libcrypto.so.0.9.8: cannot open shared object file: No such file or directory

**Comment by SGrondin** [comment]
Hey @jupalls 

Can you confirm that the lib folder that comes with HARchiver is located in the same directory? On startup, HARchiver loads those libraries.

**Comment by SGrondin** [comment]
Also please copy paste the output of `ldd harchiver` and `ldd --version`. Thanks!

**Comment by SGrondin** [comment]
No response, I'll reopen if/when we get more information.
